env:
  - CPM_SOURCE_CACHE=$HOME/cpm_source_cache
  - MSBUILD_PATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin"

language: cpp

os:
  - windows
  - osx
  - linux

dist: focal

install:
- |-
  case $TRAVIS_OS_NAME in
    windows)
      choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      export PATH=$MSBUILD_PATH:$PATH
      choco upgrade cmake
      ;;
    osx)
      brew upgrade cmake
      ;;
    linux)
      DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
      mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
      travis_retry wget --no-check-certificate https://cmake.org/files/v3.20/cmake-3.20.0-linux-x86_64.tar.gz
      tar -xvf cmake-3.20.0-linux-x86_64.tar.gz > /dev/null
      mv cmake-3.20.0-linux-x86_64 cmake-install
      PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
      cd ${TRAVIS_BUILD_DIR}
      ;;
  esac

before_cache:
  case $TRAVIS_OS_NAME in
    osx)
      brew cleanup
      ;;
  esac

script:
  - cmake . 
  - cmake --build .

cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - $HOME/Library/Caches/Homebrew
    - $CPM_SOURCE_CACHE
