env:
  - CPM_SOURCE_CACHE=$HOME/cpm_source_cache

language: cpp

branches:
  only:
  - travis

os:
  - windows
  - osx
  - linux

install:
- |-
  case $TRAVIS_OS_NAME in
    windows)
      choco install visualstudio2019buildtools
      choco upgrade cmake
      ;;
    osx)
      brew upgrade cmake
      ;;
    linux)
      sudo apt purge --auto-remove cmake
      wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
      sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
      sudo apt update
      sudo apt install cmake
      ;;
  esac

script:
  - cmake . 
  - cmake --build .

cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - $CPM_SOURCE_CACHE