language: cpp

branches:
  only:
  - travis

os:
  - windows
  - osx
  - linux

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; choco install visualstudio2019buildtools
  - choco upgrade cmake

script:
 - cmake .
 - cmake --build .