name: Build Windows
on: [push]
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set CPM_SOURCE_CACHE
        run: echo "CPM_SOURCE_CACHE=%userprofile%/cpm_source_cache" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - run: echo "${{ env.CPM_SOURCE_CACHE }}"