name: Build Linux
on: [push]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Restore CPM sources cache
        uses: actions/cache@v2
        env:
          cache-name: cache-cpm-sources
        with:
          path: "cpm_source_cache"
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Configure
        run: cmake . -DCPM_SOURCE_CACHE=cpm_source_cache
      - name: Build
        run: cmake --build . --Config Release