name: Build Windows
on: [push]
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: Get latest version
        run: echo "WAVPACK_MASTER_REF=$((git ls-remote https://github.com/colugomusic/wavpack.git master).split()[0]) | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - run: echo ${{ env.WAVPACK_MASTER_REF }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Restore CPM sources cache
        uses: actions/cache@v2
        env:
          cache-name: cache-cpm-sources
        with:
          path: "cpm_source_cache"
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Configure
        run: cmake . -DCPM_SOURCE_CACHE=cpm_source_cache
      - name: Build
        run: cmake --build . --Config Release