name: Build Windows
on: [push]
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache CPM sources
        uses: actions/cache@v2
        env:
          cache-name: cache-cpm-sources
        with:
          path: "%userprofile%/cpm_source_cache"
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
      - name: Configure
        run: cmake . -DCPM_SOURCE_CACHE=%userprofile%/cpm_source_cache